#pragma once

#include "allegro5/allegro.h"

typedef enum DITHER_PATTERN
{
    DITHER_NONE=0,
    DITHER_FILL=1,
    DITHER_HALF=2,
    DITHER_QUARTER=4,
    DITHER_EIGTH=8,

    DITHER_VERTICAL_HALF,
    DITHER_VERTICAL_QUARTER,
    DITHER_VERTICAL_EIGTH,


    DITHER_HORIZONTAL_HALF,
    DITHER_HORIZONTAL_QUARTER,
    DITHER_HORIZONTAL_EIGTH,

    DITHER_STAR_HALF,
    DITHER_STAR_QUARTER,
    DITHER_STAR_EIGTH

} DITHER_PATTERN;
typedef enum Color
{
    COLOR_DEFAULT = 0, //COLOR_DEFAULT inherits whoever owns the object's color
    COLOR_BG,
    COLOR_FRIENDLY,
    COLOR_ENEMY,
    COLOR_GROUND,
    COLOR_POISON,
    COLOR_HEAL,
    COLOR_DAMAGE
} Color;

ALLEGRO_COLOR BG;
ALLEGRO_COLOR FRIENDLY;
ALLEGRO_COLOR ENEMY;
ALLEGRO_COLOR GROUND;
ALLEGRO_COLOR WHITE;

ALLEGRO_COLOR POISON;
ALLEGRO_COLOR HEAL;
ALLEGRO_COLOR DAMAGE;

ALLEGRO_COLOR GetColor(Color c, int objectOwnedBy);
Color ALColorToCol(ALLEGRO_COLOR c);
void InitColors();
bool AlColIsEq(ALLEGRO_COLOR c, ALLEGRO_COLOR c2);
